### PR TITLE
Use strict mode

### PR DESCRIPTION
**Pull request by TonyBogdanov**
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### CODE REVIEW

**Comment by LucaMele** [comment]
Please can you merge this as it fixes the issue for me as well

**Review by LucaMele — APPROVED** [review]

**Comment by AndyOGo** [comment]
@josh 
Any chance that you look into this?

**Comment by josh** [comment]
Sorry, the oldest supported Node is 8.9.3 LTS.

**Comment by AndyOGo** [comment]
@josh 
Thanks for your response.
Agreed regarding LTS, though a bummer that you refuse to merge that one liner

**Comment by josh** [comment]
> Agreed regarding LTS, though a bummer that you refuse to merge that one liner

It's not just a "one liner". It's a commitment to test and maintain Node 4.x into the future. Any change needs to consider if APIs, syntax, and dependencies are supported in 4.x.

**Comment by AndyOGo** [comment]
Thanks for your quick reply.

I got your point.
Anyways I advocate for babel plugins to stick to supported node versions of Babel itself, which is defined here:
https://github.com/babel/babel/blob/master/package.json#L66

>"engines": {
    "node": ">= 4.x <= 9.x",
    "npm": ">= 2.x <= 5.x",
    "yarn": ">=0.27.5 || >=1.0.0-20170811"
},

**Comment by LucaMele** [comment]
Josh i cant see that you have to commit to support node 4.x if u merge that pull request. You still can say that only above 8.9.3 is supported. That line won’t change anything in new versions but helps out older versions. You don’t have to test all the older versions as you can still say older versions are not supported

**Pull request closed without merging**
